apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
spec:
  selector:
    app: jellyfin
  ports:
  - name: http
    protocol: TCP
    port: 8096
    targetPort: 8096
  #... (other ports here)
  type: LoadBalancer