# apps/qbittorrent/qbittorrent-manifest.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: gluetun
          image: qmcgaw/gluetun:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "mullvad"
            - name: VPN_TYPE
              value: "wireguard"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: mullvad-vpn
                  key: private-key
            - name: WIREGUARD_ADDRESSES
              value: "10.71.166.245/32,fc00:bbbb:bbbb:bb01::8:a6f4/128"
            - name: SERVER_COUNTRIES
              value: "Canada"
            - name: FIREWALL_INPUT_PORTS
              value: "8080"
            # Allows Gluetun to see your local NAS and Cluster IPs
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.10.5.0/24,10.0.0.0/8" 
            # Allows Traefik/Service traffic to reach the pod
            - name: NETWORK
              value: "10.10.5.0/24,10.0.0.0/8"
          ports:
            - containerPort: 8080
              name: webui
          volumeMounts:
            - name: gluetun-data
              mountPath: /gluetun

        - name: qbittorrent
          image: linuxserver/qbittorrent:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
            - name: WEBUI_PORT
              value: "8080"
            # FIXES THE 404 NOT FOUND:
            - name: QBITTORRENT__WebUI__CSRFProtection
              value: "false"
            - name: QBITTORRENT__WebUI__HostHeaderValidation
              value: "false"
            - name: QBITTORRENT__WebUI__LocalHostAuthentication
              value: "false"
            - name: QBITTORRENT__WebUI__TrustedProxies
              value: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "250m"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
        - name: gluetun-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
spec:
  selector:
    app: qbittorrent
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`qbit.servers.local`)
      kind: Rule
      services:
        - name: qbittorrent
          port: 8080