apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
spec:
  selector:
    app: jellyfin
  ports:
  - name: http
    protocol: TCP
    port: 8096
    targetPort: 8096
  - name: https
    protocol: TCP
    port: 8920
    targetPort: 8920
  - name: discovery-udp
    protocol: UDP
    port: 7359
    targetPort: 7359
  - name: client-discovery-udp
    protocol: UDP
    port: 1900
    targetPort: 1900
  type: LoadBalancer # Use NodePort if a LoadBalancer is not available in your environment