apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          securityContext:
            privileged: true
          ports:
            - containerPort: 8096
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
            - name: movies
              mountPath: /media/movies
            - name: shows
              mountPath: /media/shows
            - name: dri
              mountPath: /dev/dri
          resources:
            limits:
              memory: "4Gi"
              cpu: "2000m"
            requests:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: movies
          persistentVolumeClaim:
            claimName: jellyfin-movies
        - name: shows
          persistentVolumeClaim:
            claimName: jellyfin-shows
        - name: dri
          hostPath:
            path: /dev/dri
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
spec:
  selector:
    app: jellyfin
  ports:
    - port: 8096
      targetPort: 8096
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jellyfin.servers.local`)
      kind: Rule
      services:
        - name: jellyfin
          port: 8096