apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun-deployment
  labels:
    app: gluetun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: "RuntimeDefault"
      containers:
      - name: gluetun
        image: qmcgaw/gluetun:latest
        envFrom:
        - configMapRef:
            name: gluetun-config
        env:
        - name: WIREGUARD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: gluetun-credentials
              key: WIREGUARD_PRIVATE_KEY
        - name: WIREGUARD_PRESHARED_KEY
          valueFrom:
            secretKeyRef:
              name: gluetun-credentials
              key: WIREGUARD_PRESHARED_KEY
        ports:
        - containerPort: 8080
        - containerPort: 6881
        - containerPort: 6789
        - containerPort: 9696
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - name: dev-net-tun
          mountPath: /dev/net/tun
      volumes:
      - name: dev-net-tun
        hostPath:
          path: /dev/net/tun
