apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun-deployment
  labels:
    app: gluetun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
        - name: gluetun
          image: qmcgaw/gluetun:latest
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "airvpn"
            - name: VPN_TYPE
              value: "wireguard"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: gluetun-credentials
                  key: privatekey
            - name: WIREGUARD_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: gluetun-credentials
                  key: addresses
            - name: WIREGUARD_PRESHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: gluetun-credentials
                  key: presharedkey
            - name: FIREWALL_INPUT_PORTS
              value: "8080,6881,6789,9696"
          ports:
            - containerPort: 8080
            - containerPort: 6881
            - containerPort: 6789
            - containerPort: 9696
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
