apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
spec:
  storageClassName: nfs-storage # Replace with your storage class name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data-pvc
spec:
  storageClassName: nfs-storage # Replace with your storage class name
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1000Gi