---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: jellyfin-config
provisioning:
  diskSelector:
    match: disk.id == 'sda'
  minSize: 5000000000 # 5GB
  maxSize: 10000000000 # 10GB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: jellyfin-media
provisioning:
  diskSelector:
    match: disk.id == 'sda'
  minSize: 500000000000 # 500GB
  maxSize: 1000000000000 # 1TB