# apps/qbittorrent/gluetun-manifest.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
        - name: gluetun
          image: qmcgaw/gluetun:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "mullvad"
            - name: VPN_TYPE
              value: "wireguard"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: mullvad-vpn
                  key: private-key
            - name: WIREGUARD_ADDRESSES
              value: "10.66.212.225/32"  # Get from Mullvad account
            - name: SERVER_COUNTRIES
              value: "USA"
          ports:
            - containerPort: 8888
              name: http-proxy
          volumeMounts:
            - name: gluetun-data
              mountPath: /gluetun
      volumes:
        - name: gluetun-data
          persistentVolumeClaim:
            claimName: gluetun-data
---
apiVersion: v1
kind: Service
metadata:
  name: gluetun
  namespace: media
spec:
  selector:
    app: gluetun
  ports:
    - port: 8888
      targetPort: 8888
  type: ClusterIP