apiVersion: v1
kind: ServiceAccount
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin
  template:
    metadata:
      labels:
        name: nvidia-device-plugin
    spec:
      serviceAccountName: nvidia-device-plugin
      priorityClassName: system-node-critical
      nodeSelector:
        nvidia.com/gpu: "true"
      tolerations:
      - operator: Exists
      containers:
      - name: nvidia-device-plugin-ctr
        image: nvcr.io/nvidia/k8s-device-plugin:v0.14.1
        securityContext:
          privileged: true
        env:
        - name: FAIL_ON_INIT_ERROR
          value: "true"
        - name: LD_PRELOAD
          value: /usr/local/glibc/usr/lib/libnvidia-ml.so.1
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: nvidia-local
          mountPath: /usr/local
        - name: dev-root
          mountPath: /dev
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: nvidia-local
        hostPath:
          path: /usr/local
      - name: dev-root
        hostPath:
          path: /dev